services:
  web:
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn Ronix.wsgi:application --bind 0.0.0.0:8010"
    volumes:
      - .:/app
    ports:
      - 8010:8010
    depends_on:
      - db_ronix
    env_file:
      - .env

  redis-test:
    image: redis:7-alpine
    restart: always

  db_ronix:
    image: postgres:16.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ronix_db
      - POSTGRES_USER=ronix_user
      - POSTGRES_PASSWORD=ronix_pass

volumes:
  postgres_data:
