version: '3.9'


services:
  web:
    build: .
    ports:
      - 8010:8010
      
  redis-test:
    image: redis:7-alpine
    restart: always

  ronix:
    build: .
    command: python manage.py runserver 0.0.0.0:8010
    volumes:
      - .:/app
    ports:
      - 8010:8010

  db_ronix:
    image: postgres:16.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ronix_db
      - POSTGRES_USER=ronix_user
      - POSTGRES_PASSWORD=ronix_pass

volumes:
  postgres_data: