# Generated by Django 5.2 on 2025-05-22 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0012_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(blank=True, choices=[(-2, 'Xatolik (Payme)'), (-1, 'Bekor qilingan (Payme)'), (1, 'Yaratilgan (Payme)'), (2, 'Tasdiqlangan (Payme)')], null=True, verbose_name='Tranzaksiya holati (Payme)')),
                ('transaction_id', models.CharField(max_length=255, null=True, verbose_name='Tranzaksiya ID')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Miqdor')),
                ('time', models.BigIntegerField(blank=True, null=True, verbose_name='Vaqt')),
                ('perform_time', models.BigIntegerField(default=0, null=True, verbose_name='Bajarilgan vaqti')),
                ('cancel_time', models.BigIntegerField(default=0, null=True, verbose_name='Bekor qilingan vaqti')),
                ('status', models.CharField(choices=[('waiting', 'Kutmoqda'), ('preauth', 'Oldindan tasdiqlash'), ('confirmed', 'Tasdiqlandi'), ('rejected', 'Rad etildi'), ('refunded', 'Qaytarildi'), ('error', 'Xato'), ('input', 'Kiritish')], max_length=30, null=True, verbose_name='Holati')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sabab')),
                ('created_at_ms', models.CharField(blank=True, max_length=255, null=True, verbose_name='Yaratilgan vaqti (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('payment_operator', models.CharField(blank=True, choices=[('Click', 'Click'), ('PAYME', 'PayMe')], default='PAYME', max_length=30, null=True, verbose_name="To'lov operatori")),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Buyurtma')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "To'lov ",
                'verbose_name_plural': "To'lovlar ",
            },
        ),
    ]
