# Generated by Django 5.2 on 2025-04-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full name')),
                ('phone', models.IntegerField(verbose_name='Phone number')),
                ('country', models.CharField(max_length=200, verbose_name='Country')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('company', models.CharField(max_length=200, verbose_name='Company')),
                ('occupation', models.CharField(max_length=200, verbose_name='Occupation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active ?')),
            ],
        ),
    ]
