# Generated by Django 5.2 on 2025-04-18 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='rate',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='review.review'),
        ),
        migrations.AlterUniqueTogether(
            name='aboutcontenttranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
