# Generated by Django 5.2 on 2025-04-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customerreview_customerreviewtranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='homebannertranslation',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='homebannertranslation',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
    ]
