# Generated by Django 5.2 on 2025-04-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('packaging', 'Packaging'), ('shipped', 'Shipped'), ('canceled', 'Canceled'), ('awaiting pickup', 'Awaiting pickup'), ('completed', 'Completed')], max_length=30, verbose_name='order_status')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('discount', models.FloatField(verbose_name='discount')),
            ],
        ),
    ]
