# Generated by Django 5.2 on 2025-05-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
