# Generated by Django 5.2 on 2025-05-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_orderitem_discount_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Total price'),
        ),
    ]
