# Generated by Django 5.2 on 2025-05-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_external_id_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('awaiting payment', 'Awaiting Payment')], default='pending', max_length=30, verbose_name='order_status'),
        ),
    ]
