# Generated by Django 5.2 on 2025-04-24 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specification',
        ),
        migrations.AddField(
            model_name='specification',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='made_in',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Made in'),
        ),
    ]
