# Generated by Django 5.2 on 2025-04-13 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.specification', verbose_name='Specification'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='capacity_steel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Capacity in steel'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='capacity_wood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Capacity in wood'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='frequency',
            field=models.CharField(max_length=100, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='power',
            field=models.CharField(max_length=100, verbose_name='Power'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='size',
            field=models.CharField(max_length=100, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='speed',
            field=models.CharField(max_length=100, verbose_name='Speed'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='supplied_in',
            field=models.CharField(max_length=100, verbose_name='Supplied in'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='voltage',
            field=models.CharField(max_length=100, verbose_name='Voltage'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='weight',
            field=models.CharField(max_length=100, verbose_name='Weight'),
        ),
    ]
