# Generated by Django 5.2 on 2025-04-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productdetail_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdetail',
            options={'verbose_name': 'Product Detail', 'verbose_name_plural': 'Product Details'},
        ),
        migrations.AlterModelOptions(
            name='productdetailtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Product Detail Translation'},
        ),
    ]
